# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c97da6664b65ebf4793774a5315bfb593e902735f1a5390d75097fde4e3d355ca147fea62e0fdf6ffff5f962dd13b9a03e56d7df86f0a97ab220f132cb50c432

test:
  secret_key_base: 691713710ca1849bdf56321a4af28abcd115c280063ce6c77ba58818a6799377d03fa48543bec0946ac0ade3a81f2f37e346895ebd4e8ae2513b891f8782a1d6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
